spring:
  application:
    name: transaction-processing-api

  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    secret: ${TXAPI_JWT_SECRET:CHANGE_ME_DEV_ONLY_SUPER_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS}
    issuer: ${TXAPI_JWT_ISSUER:txapi}
    ttl-minutes: ${TXAPI_JWT_TTL_MINUTES:60}